# Generated by Django 5.2.7 on 2025-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Enter level from 0 to 100', max_length=100, null=True),
        ),
    ]
